modLoader="javafml"
license="LGPLv3"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Trinsdar/Cinderscapes-Reforged/issues"

[[mods]]
modId="cinderscapes"
version="${version}"
displayName="Cinderscapes Reforged"
displayURL="https://github.com/Trinsdar/Cinderscapes-Reforged"
credits="TerraformersMC for creating the fabric version"
authors="Trinsdar, Vaerian, NeusFear, TerraformersMC"
description='''An expansion of Minecraft's Nether biomes!'''
[[dependencies.cinderscapes]]
modId="forge"
mandatory=true
versionRange="[43.2.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.cinderscapes]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="AFTER"
side="BOTH"