modLoader="javafml"
license="LGPLv3"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Trinsdar/Cinderscapes-Reforged/issues"

[[mods]]
modId="cinderscapes"
version="${version}"
displayName="Cinderscapes"
displayURL="https://github.com/Trinsdar/Cinderscapes-Reforged"
credits="TerraformersMC for creating the fabric version"
authors="Trinsdar, Vaerian, NeusFear, TerraformersMC"
description='''An expansion of Minecraft's Nether biomes!'''
[[dependencies.cinderscapes]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.cinderscapes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.cinderscapes]]
    modId="nebi"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"