modLoader="javafml"
license="LGPLv3"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Trinsdar/Cinderscapes-Reforged/issues"

[[mods]]
modId="cinderscapes_client"
version="${version}"
displayName="Cinderscapes: Client Reforged"
displayURL="https://github.com/Trinsdar/Cinderscapes-Reforged"
credits="TerraformersMC for creating the fabric version"
authors="Trinsdar, Vaerian, NeusFear, TerraformersMC"
description='''An expansion of Minecraft's Nether biomes!'''
[[dependencies.cinderscapes_client]]
modId="forge"
mandatory=true
versionRange="[40.1.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.cinderscapes_client]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="AFTER"
side="BOTH"