modLoader="javafml"
license="LGPLv3"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Trinsdar/Cinderscapes-Reforged/issues"

[[mods]]
modId="cinderscapes_worldgen"
version="${version}"
displayName="Cinderscapes: World Generation Reforged"
displayURL="https://github.com/Trinsdar/Cinderscapes-Reforged"
credits="TerraformersMC for creating the fabric version"
authors="Trinsdar, Vaerian, NeusFear, TerraformersMC"
description='''An expansion of Minecraft's Nether biomes!'''
[[dependencies.cinderscapes_worldgen]]
modId="forge"
mandatory=true
versionRange="[40.1.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.cinderscapes_worldgen]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="AFTER"
side="BOTH"
[[dependencies.cinderscapes_worldgen]]
modId="fabric_biome_api"
mandatory=true
versionRange="[2.0.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.cinderscapes_worldgen]]
modId="terraform"
mandatory=true
versionRange="[3.1.0,)"
ordering="AFTER"
side="BOTH"